export const PERFORMANCE_BUDGETS = {
  CRITICAL_JS_KB: 170,
  TOTAL_INITIAL_JS_KB: 200,
  CSS_KB: 15,
  TTI_3G_MS: 5000,
  LCP_MS: 2500,
  APP_SHELL_PRECACHE_KB: 200,
  LESSON_CONTENT_MAX_KB: 100,
  SERVICE_WORKER_KB: 15,
  MAIN_ENTRY_CHUNK_KB: 50,
  LARGEST_VENDOR_CHUNK_KB: 120,
} as const;

export const NETWORK_TIMEOUTS = {
  '4g': 3000,
  '3g': 8000,
  '2g': 15000,
  'slow-2g': 15000,
  'unknown': 8000,
} as const;

export const AUTH = {
  ACCESS_TOKEN_EXPIRY_SECONDS: 900,
  REFRESH_TOKEN_EXPIRY_SECONDS: 604800,
  BCRYPT_COST_FACTOR: 12,
  MAX_LOGIN_ATTEMPTS: 5,
  LOGIN_WINDOW_MINUTES: 15,
  LOCKOUT_MINUTES: [5, 15, 60],
  PASSWORD_RESET_TOKEN_EXPIRY_HOURS: 1,
} as const;

export const SYNC = {
  RESERVED_PARTITION_BYTES: 5 * 1024 * 1024,
  STORAGE_WARNING_THRESHOLD: 0.8,
  THROUGHPUT_SAMPLE_COUNT: 5,
  MAX_OFFLINE_COURSES: 10,
} as const;

export const PAYMENT = {
  PAYSTACK_FEE_PERCENT: 1.5,
  PAYSTACK_FLAT_FEE_NGN: 100,
  PAYSTACK_FEE_CAP_NGN: 2000,
  PAYSTACK_SMALL_TXN_THRESHOLD_NGN: 2500,
  VAT_RATE: 0.075,
  DUNNING_SCHEDULE_HOURS: [24, 72, 168],
  GRACE_PERIOD_DAYS: 7,
} as const;

export const CONTENT = {
  MIN_QUIZ_ITEMS_PER_LESSON: 3,
  MAX_QUIZ_ITEMS_PER_LESSON: 5,
  MIN_APPLICATION_QUIZ_PERCENT: 40,
  WORD_COUNT_MAX_PER_BLOCK: 300,
  DIFFICULTY_TIERS: ['beginner', 'intermediate', 'advanced'] as const,
} as const;
