// ── Table Names ─────────────────────────────────────────────────────────────

export const TABLES = {
  USERS: 'users',
  LEARNER_PROGRESS: 'learner_progress',
  ASSESSMENT_ATTEMPTS: 'assessment_attempts',
  CONSENT_RECORDS: 'consent_records',
  ORGANIZATIONS: 'organizations',
  DEPARTMENTS: 'departments',
  COURSE_CATEGORIES: 'course_categories',
  COURSES: 'courses',
  MODULES: 'modules',
  LESSONS: 'lessons',
  ENROLLMENT: 'enrollment',
  SUBSCRIPTION_PLANS: 'subscription_plans',
  SUBSCRIPTIONS: 'subscriptions',
  PAYMENT_TRANSACTIONS: 'payment_transactions',
  INVOICES: 'invoices',
  DUNNING_ATTEMPTS: 'dunning_attempts',
  CREDENTIAL_TEMPLATES: 'credential_templates',
  ISSUED_CREDENTIALS: 'issued_credentials',
  SEAT_ALLOCATIONS: 'seat_allocations',
  DEPARTMENT_SEAT_ALLOCATIONS: 'department_seat_allocations',
  WHATSAPP_SUBSCRIPTIONS: 'whatsapp_subscriptions',
  WHATSAPP_MESSAGES: 'whatsapp_messages',
  WHATSAPP_TEMPLATES: 'whatsapp_templates',
  BULK_ENROLLMENT_JOBS: 'bulk_enrollment_jobs',
  BULK_ENROLLMENT_ERRORS: 'bulk_enrollment_errors',
} as const;

// ── Key Columns ─────────────────────────────────────────────────────────────

export const COLUMNS = {
  users: {
    id: 'id',
    email: 'email',
    phone_number: 'phone_number',
    first_name: 'first_name',
    last_name: 'last_name',
    password_hash: 'password_hash',
    role: 'role',
    org_id: 'org_id',
    department_id: 'department_id',
    language_preference: 'language_preference',
    data_saver_mode: 'data_saver_mode',
    email_verified: 'email_verified',
    is_active: 'is_active',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  consent_records: {
    id: 'id',
    user_id: 'user_id',
    consent_type: 'consent_type',
    granted: 'granted',
    version: 'version',
    ip_address: 'ip_address',
    user_agent: 'user_agent',
    created_at: 'created_at',
  },
  organizations: {
    id: 'id',
    name: 'name',
    slug: 'slug',
    industry: 'industry',
    size_category: 'size_category',
    is_active: 'is_active',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  departments: {
    id: 'id',
    org_id: 'org_id',
    name: 'name',
    created_at: 'created_at',
  },
  courses: {
    id: 'id',
    title: 'title',
    slug: 'slug',
    category_id: 'category_id',
    difficulty_level: 'difficulty_level',
    is_published: 'is_published',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  lessons: {
    id: 'id',
    module_id: 'module_id',
    course_id: 'course_id',
    title: 'title',
    sort_order: 'sort_order',
    estimated_duration_minutes: 'estimated_duration_minutes',
    is_published: 'is_published',
  },
  enrollment: {
    id: 'id',
    user_id: 'user_id',
    course_id: 'course_id',
    org_id: 'org_id',
    enrollment_type: 'enrollment_type',
    status: 'status',
    enrolled_at: 'enrolled_at',
    completed_at: 'completed_at',
  },
  subscriptions: {
    id: 'id',
    user_id: 'user_id',
    org_id: 'org_id',
    plan_id: 'plan_id',
    status: 'status',
    current_period_start: 'current_period_start',
    current_period_end: 'current_period_end',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
} as const;

// ── Type Helpers ────────────────────────────────────────────────────────────

export type TableName = (typeof TABLES)[keyof typeof TABLES];
export type ColumnDef<T extends keyof typeof COLUMNS> = (typeof COLUMNS)[T];
